### ISSUE TITLE
Component - File uploader

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-React-UI#10]
_Design review: 4.5-Input:_ https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=494%3A6768&t=f9u4O5zfC6AWcOah-4
_Test URL_: https://ui-preview.subwallet.app/?path=/story/form-single-file-dragger--default

**Comment by sokol142** [comment]
_Design review: 4.5: Input_
Please check:

- [x] Missing the component when active
- [x] Recheck with design

![Image](https://user-images.githubusercontent.com/102292476/211961247-e0a2dd0d-6bea-4746-97c9-9e49401e507a.png)

**Comment by sokol142** [comment]
Require design for case: error file

**Comment by sokol142** [comment]
@lw-cdm The design is already available: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=1543%3A10136&t=FPAfgCVBcWQtUJz0-4

- [x] Please update the components in case the file is error => Implement when upgrade UI for extension
