### ISSUE TITLE
Component - Select (Modal)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#15]
- Design url:
  - [https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=40%3A585&t=V3pON2doS3jRLbcX-0](https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=40%3A585&t=V3pON2doS3jRLbcX-0)
- Test url: [https://ui-preview.subwallet.app/?path=/story/modal-selectmodal--primary](https://ui-preview.subwallet.app/?path=/story/modal-selectmodal--primary)

**Comment by sokol142** [comment]
_Design review: 5.6-Modal_
Please check:

- [x] SelectModal: Add the hover properties when hover an item on list
![image](https://user-images.githubusercontent.com/102292476/212011449-fca615cd-c6a0-4abe-91af-38d6ad02cddb.png)

- [x] SelectModal: Add the "Title" control for the select box
![image](https://user-images.githubusercontent.com/102292476/212013758-bd13a58c-c5f6-46d7-b529-093e13be7bdf.png)

**Comment by sokol142** [comment]
- [x] Update color
![image](https://user-images.githubusercontent.com/102292476/215013817-b455213d-17b5-4f8b-9421-3b3d27b1c7a9.png)

- [x] Ui bug in case the Title is long
![image](https://user-images.githubusercontent.com/102292476/215014781-e049438c-3483-4a73-aa5e-508ba23f05af.png)

- [x] add the "Custom suffix" control
- [x] add the "default placeholder"
- [x] update the "default title"
- [x] Require design: size input incase without title
- [x] add the "prefix" control

**Comment by sokol142** [comment]
Please check:

- [x] UI bug when have no title
![image](https://user-images.githubusercontent.com/102292476/215985807-4be47d07-c2b6-4f3b-ac97-450293c7e04f.png)

- [x] Add the "custom suffix/ custom prefix/ full custom with label": https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=68%3A1382&t=9uLf2FlrzlUg8T7q-4
![image](https://user-images.githubusercontent.com/102292476/215992783-41643d55-987e-4800-b35c-e1afbbc4a0c8.png)
