### ISSUE TITLE
Component - Image

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#26]
Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=142%3A4563&t=tpBNXokKY0HhEGG6-0

**Comment by sokol142** [comment]
_Design review: 4.6-Image_

Please check:

- [x] Squircle not support pre-view image => Do not use pre-view control => hide this control
- [x] Add "loading" control (**_require design_**)
- [x] Add "fault tolerant" control (Load failed to display image placeholder) (**_require design_**)

**Comment by sokol142** [comment]
@Quangdm-cdm The design is already available: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=1551%3A10356&t=GUP3KWR7KTsuzoAC-4

- [x] Please update component with loading & fault tolerant control
