### ISSUE TITLE
Screen - Pincode

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#27]
Design: 4.5-Input 
https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=136%3A5442&t=tpBNXokKY0HhEGG6-0

**Comment by sokol142** [comment]
Please check:

- [x] UI bug => implement when custom mobile app
![image](https://user-images.githubusercontent.com/102292476/212057184-715b8323-b2e1-49a9-8cc4-85f2b49c6791.png)

- [x] Require design: Add status control (include: success, failed, undefined)
=> Solution: Show message
