### ISSUE TITLE
Component - Modal

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#33]
- Design url: [https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=512%3A7736&t=xUY5tMM8fAwlcAyP-0](https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=512%3A7736&t=xUY5tMM8fAwlcAyP-0)
- Test url: [https://ui-preview.subwallet.app/?path=/story/modal-swmodal--primary](https://ui-preview.subwallet.app/?path=/story/modal-swmodal--primary)

**Comment by sokol142** [comment]
_Design review: 5.6-Modal_
Please check:
- [x] SwModal -Default > footerElement = 0: Incorrect buttonColor
![image](https://user-images.githubusercontent.com/102292476/211986457-b4dd844a-9bb0-4a3a-a5ff-9479bdcc995a.png)

- [x] SwModal: Incorrect Icon's color
![image](https://user-images.githubusercontent.com/102292476/212016597-28ad87de-4ebd-4263-a88e-4e5161045199.png)

- [x] SwModal - Warning: font-size of the warning icon is incorrect
![image](https://user-images.githubusercontent.com/102292476/212022624-8fc7e6d5-e027-46f5-af83-d7678a7d5a32.png)

- [x] SwModal - Warning/Danger: Cannot hide the Close (X) button & can not use maskClosable
![image](https://user-images.githubusercontent.com/102292476/212023735-cb84eaac-2db5-442e-896f-5a5ef0ba98c1.png)

**Comment by sokol142** [comment]
- [ ] Update color
![image](https://user-images.githubusercontent.com/102292476/215013817-b455213d-17b5-4f8b-9421-3b3d27b1c7a9.png)
