### ISSUE TITLE
Component - QR

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#34]
Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=306%3A5400&t=tpBNXokKY0HhEGG6-0
Test URL: https://ui-preview.subwallet.app/?path=/story/basic-components-qrcode--default&globals=backgrounds.value:!hex(1A1A1A)

**Comment by sokol142** [comment]
Please check:

- [x] QR with icon can not scan (Example: Scan with value = an address)

**Comment by Quangdm-cdm** [comment]
If use QRCode with icon, please use property errorLevel "Q" or "H". The ratio between Icon and QRCode is 1/4

**Comment by sokol142** [comment]
- [x] Remove "bordered" control if not use them
