### ISSUE TITLE
Component - Logo

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#35]
Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=36%3A489&t=tpBNXokKY0HhEGG6-0

- [x] Network Logo

**Comment by sokol142** [comment]
Design review: 3.2-Account & Network
Please review some suggest below:

- [x] Grouping avatar & subIcon
![image](https://user-images.githubusercontent.com/102292476/212037048-8813a5e0-c35e-4ef3-838a-a8721215b4e1.png)
