### ISSUE TITLE
Component - Avatar (Account Identicon)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#36]
Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=36%3A489&t=tpBNXokKY0HhEGG6-0
URL test: https://ui-preview.subwallet.app/?path=/story/basic-components-swavatar--default

**Comment by sokol142** [comment]
_Design review: 3.2-Account & Network_
Please review some suggest below:
- [x] Add a control to generate/show avatar for the "all account"
- [x] Grouping avatar & subIcon

**Comment by sokol142** [comment]
Confirm & require for All account mode (account group)
=> All accounts implement when upgrade ui for extension.
