### ISSUE TITLE
Component - QR Scanner

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#38]
Design: 4.7-QR

- Test url: [https://ui-preview.subwallet.app/?path=/story/qr-swqrscanner--default](https://ui-preview.subwallet.app/?path=/story/qr-swqrscanner--default)
- Design url:
  - [https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=842%3A8490&t=V3pON2doS3jRLbcX-0](https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=842%3A8490&t=V3pON2doS3jRLbcX-0)
  - [https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=494%3A16435&t=q1cWwnJFFcxpa44I-0](https://www.figma.com/file/2nYhrm0rlJtfJoMwrT51Ep/SubWallet-Apps?node-id=494%3A16435&t=q1cWwnJFFcxpa44I-0)

**Comment by sokol142** [comment]
Please check:

- [x] Incorrect color of the MultiFrame bar
![image](https://user-images.githubusercontent.com/102292476/212622522-50106226-6ed6-4f53-a77f-3233b3efe72e.png)

- [x] Re-check icon follow by design
![image](https://user-images.githubusercontent.com/102292476/212623380-0f4e9921-a02f-46f8-8850-72c0e9b24276.png)

- [x] UI bug
![image](https://user-images.githubusercontent.com/102292476/212626393-4253211a-5344-4f85-880f-405dd35fcb13.png)

**Comment by sokol142** [comment]
- [x] Re-check the camera list in case denied camera
![image](https://user-images.githubusercontent.com/102292476/214996389-c3fe4770-41fe-4d92-9153-131979c86ab2.png)

- [x] When close modal then close stream camera
![image](https://user-images.githubusercontent.com/102292476/215017641-8de1c0d5-bb54-49c0-b3a3-5ad20408e0ea.png)

- [x] Bug display the scan frame on the Firefox browser
![image](https://user-images.githubusercontent.com/102292476/215036089-35e084cd-caaf-4c74-bfa8-698d1ef57ccb.png)

**Comment by sokol142** [comment]
- [x] Handle case have no camera
- [x] Handle case denied camera on the firefox browser
- [x] Do not show value on the select camera dropdown on the firefox browser
![image](https://user-images.githubusercontent.com/102292476/216013298-dae05b1b-d02d-4e71-b34f-25a27cc260f8.png)

**Comment by sokol142** [comment]
- [x] Do not show camera name on the Select camera screen when use Firefox browser
![image](https://user-images.githubusercontent.com/102292476/218926004-e011d046-4ec2-42ba-9c76-f57a983c1a4d.png)

- [x] Bug when use Safari browser
![38_SafariBug](https://user-images.githubusercontent.com/102292476/218930667-5e65b1b7-11b7-420c-9349-94c892e4db63.gif)

- [x] Can't access camera on Opera browser => This browser do not support, review & improve later
![image](https://user-images.githubusercontent.com/102292476/218935496-869e00e1-49b6-46a2-af79-62557b1e72f5.png)

**Comment by sokol142** [comment]
Test later when testing upgrade UI for extension
