### ISSUE TITLE
Component - Search

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#39]
Design review: 4.5-Input: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=68%3A1291&t=Io7xuX68iDDjrWCs-4
URL test: https://ui-preview.subwallet.app/?path=/story/form-search--default

**Comment by sokol142** [comment]
_Design review: 4.5-Input_
Please check:

- [x] Add the Closeable control to clear search key

**Comment by sokol142** [comment]
Confirming "clear keyword" design

**Comment by sokol142** [comment]
@lw-cdm The design is already available: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=1551%3A10268&t=FPAfgCVBcWQtUJz0-4

- [x] Please update the search box with cleard keyword button

**Comment by saltict** [comment]
- [x] Add filter icon and onClick of filter icon
