### ISSUE TITLE
Component - Button

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-React-UI#4]
Design review: 1.1-Button

**Comment by sokol142** [comment]
_Design review: 1.1-Button_
Please check:
- [x] Incorrect hove & active color in case: Schema = warning
![image](https://user-images.githubusercontent.com/102292476/211972838-fe69a701-684d-4ecf-8442-8d36e72a45a2.png)

- [x] Icon: should be remove "contentAlign" control
![image](https://user-images.githubusercontent.com/102292476/211973235-55be2a70-ee37-4c33-9157-4794c279e875.png)

- [x] Ghost icon with text: incorrect hover color and active color
- [x] Ghost icon, ghost icon with text: when click on button then show border (see file below)

![Image](https://user-images.githubusercontent.com/102292476/212805296-439a7451-4ed7-40f0-8fb6-9811da2bba7e.png)
