### ISSUE TITLE
Component - Toast

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#40]
Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=494%3A6769&t=tpBNXokKY0HhEGG6-0
Test URL: https://ui-preview.subwallet.app/?path=/story/basic-components-notification--default

**Comment by sokol142** [comment]
Please check:

- [x] Do not show toast when select type control = default
- [x] Show incorrect icon color with type = success/warning/error when using Notification with icon

![Image](https://user-images.githubusercontent.com/102292476/211801862-b3060312-3514-4ff9-a99f-29968a04d648.png)

- [x] UI bug when the message is long


![Image](https://user-images.githubusercontent.com/102292476/211959795-6f42cc93-5acb-4913-a1ec-cf89357a557f.png)

**Comment by Quangdm-cdm** [comment]
Show incorrect icon color with type = success/warning/error when using Notification with icon is not a bug. It's an example about notification with icon @sokol142

**Comment by sokol142** [comment]
- [x] Show incorrect UI when using vertical direction on the Default mode
![image](https://user-images.githubusercontent.com/102292476/215066230-ad024008-39df-416e-b5ab-19c1773cf17a.png)
