### ISSUE TITLE
Component - Tabbar (Navigation bar)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#41]
Design: 2.4-Tabbar

- [x] Extension Tabbar

- Design url: [https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=69%3A2534&t=V3pON2doS3jRLbcX-0](https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=69%3A2534&t=V3pON2doS3jRLbcX-0)
- Test url: [https://ui-preview.subwallet.app/?path=/story/layout-swtabbar--primary](https://ui-preview.subwallet.app/?path=/story/layout-swtabbar--primary)

**Comment by sokol142** [comment]
Please check:
- Icon:
![image](https://user-images.githubusercontent.com/102292476/212040785-f8a9a3c3-477d-49d3-ba69-5a5bb5c05831.png)
