### ISSUE TITLE
Component - Header

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#42]
Design: 2.3-Navigation bar

- [x] Extension header

- Test url:
  - [https://ui-preview.subwallet.app/?path=/story/layout-swsubheader--primary](https://ui-preview.subwallet.app/?path=/story/layout-swsubheader--primary)
  - [https://ui-preview.subwallet.app/?path=/story/layout-swheader--primary](https://ui-preview.subwallet.app/?path=/story/layout-swheader--primary)

- Design url: [https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=66%3A1252&t=V3pON2doS3jRLbcX-0](https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=66%3A1252&t=V3pON2doS3jRLbcX-0)

**Comment by sokol142** [comment]
Please check:
**Header**
- [x] UI bug
![image](https://user-images.githubusercontent.com/102292476/212042288-c853be64-baf6-4c21-8439-4a4f38036682.png)
![image](https://user-images.githubusercontent.com/102292476/212047794-84da5c84-a6d0-4121-bd95-9a06bfe493d4.png)

**Sub-header**
![image](https://user-images.githubusercontent.com/102292476/212049684-745288f7-6b7d-41eb-bae6-f6bf69750b14.png)
![image](https://user-images.githubusercontent.com/102292476/212050454-72b298a2-b9e8-4067-acee-fce3670bded4.png)

**Comment by sokol142** [comment]
- [x] Update padding in case Center = True and rightIconType = 0
![image](https://user-images.githubusercontent.com/102292476/215247976-8dd2f3ce-04da-4130-9a69-9b2c8757ca88.png)

- [x] Recheck center control

**Comment by sokol142** [comment]
Please check:

- [x] Update padding
![image](https://user-images.githubusercontent.com/102292476/215996303-8a096024-c6b2-45a7-9e99-9213e7cbbce9.png)
