### ISSUE TITLE
List Screen - SW List (base on flatlist)

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#43]
Design: 3.3-Lists: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=83%3A1959&t=Io7xuX68iDDjrWCs-4
Test URL: https://ui-preview.subwallet.app/?path=/story/layout-swlist--default&globals=backgrounds.value:!hex(1A1A1A)

**Comment by sokol142** [comment]
Design review: 3.2-Lists
Please check and update:

- [x] Add the "Loading" control
- [x] Add the cursor
- [x] UI bug on Display Grid component when search:

![Image](https://user-images.githubusercontent.com/102292476/212630884-ee3872dd-9d4e-4462-acec-bcbf9937f2f4.png)

**Comment by sokol142** [comment]
- [x] Spacing of the loading icon 
![image](https://user-images.githubusercontent.com/102292476/215069772-7414bab0-da60-4f48-8f34-f57941f26194.png)

- [x] @Quangdm-cdm Update style with divider
![image](https://user-images.githubusercontent.com/102292476/215070529-836f1cdf-0e57-474b-9cdb-1e50a2123a48.png)

- [x] @Quangdm-cdm Ui in case have scroll bar
![image](https://user-images.githubusercontent.com/102292476/215074512-02966470-1ccb-4437-a8fe-2658aa5631f3.png)

**Comment by sokol142** [comment]
- [x] Please update the empty component
@lw-cdm @Quangdm-cdm The design is already available: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=1555%3A10405&t=6I5CTTZl5vxJUokz-4

- [x] Please update padding
![image](https://user-images.githubusercontent.com/102292476/219017761-94fcd125-5d6e-49c0-9e13-b01c4a62ba87.png)

**Comment by saltict** [comment]
- [x] Search logic need wrap all item in the list (not only what appear in the list)
