### ISSUE TITLE
Layout - Screen layout

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#49]
Design: 6.2-Extension
Test url: (https://ui-preview.subwallet.app/?path=/story/layout-swscreenlayout--header-with-tab-bar)
Design url: [https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=68%3A1403&t=V3pON2doS3jRLbcX-0](https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=68%3A1403&t=V3pON2doS3jRLbcX-0)

**Comment by sokol142** [comment]
Please check;
![image](https://user-images.githubusercontent.com/102292476/212052975-51e2bf73-aead-4d69-b284-2daab45d94b1.png)

**Comment by sokol142** [comment]
Please check:

- [x] UI bug 
![image](https://user-images.githubusercontent.com/102292476/212053673-007912aa-1b89-48fc-9b18-234efb2ef70f.png)
![image](https://user-images.githubusercontent.com/102292476/212054072-c41c9b33-69d3-4196-8e06-612199248389.png)

**Comment by sokol142** [comment]
Please check:

- [x] Confirm: hoverColor
![image](https://user-images.githubusercontent.com/102292476/213152308-5bce7ce5-916c-4be0-a853-100e52d76ddf.png)

- [x] Bug UI 
![image](https://user-images.githubusercontent.com/102292476/213154099-a1b130f3-7992-4853-8a0d-cb5834c86cb6.png)

**Comment by sokol142** [comment]
- [x] Re-check subHeaderCenter
![image](https://user-images.githubusercontent.com/102292476/215248455-e0b2bb1f-88b2-4ac0-870d-d5affed8fb60.png)

- [x] Add the "divider" control
![image](https://user-images.githubusercontent.com/102292476/215252794-8144b688-06f3-4889-97da-e004a5fbe948.png)

- [x] Update the menu icon follow-up design
![image](https://user-images.githubusercontent.com/102292476/215252860-f0801a00-716b-440d-adc1-71502b9b8b0a.png)

- [x] Add the "footer" control: 
- https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=701%3A7715&t=ldXlNCCOIhELeZmm-4

- [x] Add the "button" control: 

- https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=717%3A7591&t=ldXlNCCOIhELeZmm-4

**Comment by sokol142** [comment]
- [x] Add padding for SubHeader Only 
- [x] Remove divider (or turn on divider control)

=> implement when upgrade UI for extension
