### ISSUE TITLE
Component - Number

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-React-UI#5]
Design review: 0.2-Typo

**Comment by sokol142** [comment]
_Design review: 0.2-Typo_
- [x] Number
- Recheck design 

![Image](https://user-images.githubusercontent.com/102292476/211970895-4477d4c4-e78f-448b-a798-b95e8daa872f.png)

**Comment by sokol142** [comment]
- [x] @Quangdm-cdm update control for the number
