### ISSUE TITLE
Component - Web3 Gallery

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#50]
- [x] Web3Gallery: https://ui-preview.subwallet.app/?path=/story/subwallet-components-image-selection--default&globals=backgrounds.value:!hex(000000)
- [x] NFT Collection Item: https://ui-preview.subwallet.app/?path=/story/subwallet-components-nft-collection--default&args=count:30&globals=backgrounds.value:!hex(000000)
- [x] NFT Item: https://ui-preview.subwallet.app/?path=/story/subwallet-components-nft-item--default&globals=backgrounds.value:!hex(000000)

**Comment by sokol142** [comment]
Design review: 3.2-Lists
Please check and update:

- [ ] Add the "Loading" control
- [ ] Add the cursor
- [ ] UI bug on Display Grid component when search:

![Image](https://user-images.githubusercontent.com/102292476/212630884-ee3872dd-9d4e-4462-acec-bcbf9937f2f4.png)
