### ISSUE TITLE
Component - Web3Block

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#51]
Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=36%3A491&t=tpBNXokKY0HhEGG6-0
- [x] Web3Block
- [x] AccountItem
- [x] #74
- [x] #75
- [x] #76
- [x] #80
- [x] #86
- [x] #81
- [x] #88
- [x] #91

**Comment by sokol142** [comment]
Require design:

- [ ] Add the option: Account Name and Address in line

![Image](https://user-images.githubusercontent.com/102292476/215258325-1ce180ed-d944-4be7-82ec-425de282a032.png)
