### ISSUE TITLE
BalanceItem

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-React-UI#74]
Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=76%3A1915&t=NqtDVXsufeoHGMOC-4

Test url: https://ui-preview.subwallet.app/?path=/story/subwallet-components-balanceitem--default

**Comment by sokol142** [comment]
- [x] Please check:

![image](https://user-images.githubusercontent.com/102292476/215375549-ec19cfe8-863b-460e-835b-2c04288f32cb.png)
