### ISSUE TITLE
CrowdloanItem

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-React-UI#75]
Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=84%3A1778&t=H5QaPceU5UReKwQP-4

Test url: https://ui-preview.subwallet.app/?path=/story/subwallet-components-crowdloanitem--default

**Comment by sokol142** [comment]
Please check:

- [x] Number style

![Image](https://user-images.githubusercontent.com/102292476/215376449-e0d72035-9d7a-4cbc-bf0a-522f84004e32.png)

**Comment by sokol142** [comment]
@Quangdm-cdm Split the color of the following 3 components:
- Number
- Float Number
- Suffix




![Image](https://user-images.githubusercontent.com/102292476/218241597-89d2fcab-3c2f-4aef-93c2-73737b8a4d9a.png)
