### ISSUE TITLE
StakingItem

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-React-UI#76]
Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=84%3A1900&t=H5QaPceU5UReKwQP-4
Test url:
- https://ui-preview.subwallet.app/?path=/story/subwallet-components-stakingitem--default&globals=backgrounds.value:!hex(1A1A1A)
- https://ui-preview.subwallet.app/?path=/story/subwallet-components-stakingnetworkitem--default&globals=backgrounds.value:!hex(1A1A1A)
- https://ui-preview.subwallet.app/?path=/story/subwallet-components-stakingvalidatoritem--default&globals=backgrounds.value:!hex(1A1A1A)

**Comment by sokol142** [comment]
Please check:

- [x] Update the default color of this icon
![image](https://user-images.githubusercontent.com/102292476/215386261-3340cdcb-ef73-4cf6-bb74-39a478028bf6.png)
- [x] Confirm designer: style number 
![image](https://user-images.githubusercontent.com/102292476/215386334-965d4fde-8e91-4030-bf36-a1f8017d72f7.png)

**Comment by sokol142** [comment]
Require design:

- [x] Staking item with staking type => Implement when upgrade UI extension
