### ISSUE TITLE
Component - Basic form input

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/SubWallet-React-UI#8]
Design review: 4.5-Input, 0.2-Typo
- Input: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=68%3A1203&t=f9u4O5zfC6AWcOah-4
- Number: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=649%3A10024&t=f9u4O5zfC6AWcOah-4
Test URL:
- [x] Text: https://ui-preview.subwallet.app/?path=/story/form-input--default
- [x] Password: https://ui-preview.subwallet.app/?path=/story/form-password--default
- [x] Number: https://ui-preview.subwallet.app/?path=/story/core-number--default
- [x] Text area: https://ui-preview.subwallet.app/?path=/story/form-textarea--default

**Comment by sokol142** [comment]
_Design review: 4.5-Input, 0.2-Typo_

Please check:
- [x] Textarea: 
- UI bug when have scroll and use shape = "Round"

![Image](https://user-images.githubusercontent.com/102292476/211969340-eeb987a5-162c-4b14-afcf-364d25ec8401.png)

- UI bug in case no label

![Image](https://user-images.githubusercontent.com/102292476/211969740-c1463e0b-a196-4872-848e-0e94b56fdf65.png)
