### ISSUE TITLE
StakingNetworkItem

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-React-UI#81]
Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=84%3A1954&t=H5QaPceU5UReKwQP-4
Test url: https://ui-preview.subwallet.app/?path=/story/subwallet-components-stakingnetworkitem--default&args=expectedReturn:0;stakingCount:9073&globals=backgrounds.value:!hex(000000)

**Comment by sokol142** [comment]
- [x] Bug: Do not show expected return control & recheck rightItem
Please check case expected return = 0 or have no expected return

![Image](https://user-images.githubusercontent.com/102292476/215396216-cf2e2213-26d2-42f4-ba4a-1c4a79d2b3f8.png)

**Comment by sokol142** [comment]
- [x] Please check case have no expected return
