### ISSUE TITLE
NetworkItem

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-React-UI#88]

**Comment by sokol142** [comment]
Please check

- [x] Update padding when using divider
![image](https://user-images.githubusercontent.com/102292476/215431567-6ed936fe-d8da-4821-849d-0a2a45710dfe.png)

**Comment by sokol142** [comment]
- [x] Separate tokenItem with NetworkItem

- [x] Please check spacing in case have/have no divider
- Expected: Same spacing
![image](https://user-images.githubusercontent.com/102292476/215955084-44948cc1-26b1-4046-9022-c66ed56bb909.png)
