### ISSUE TITLE
Setting Item

### ISSUE THREAD

**Issue by Quangdm-cdm** [Koniverse/SubWallet-React-UI#91]
Design: https://www.figma.com/file/eOUqz887O5EKZwIJhJQ13U/SubWallet-UI-Base?node-id=83%3A1959&t=H5QaPceU5UReKwQP-4
Test url: https://ui-preview.subwallet.app/?path=/story/subwallet-components-settingitem--default&globals=backgrounds.value:!hex(000000)

**Comment by sokol142** [comment]
Please check:

- [x] Padding when use divider
![image](https://user-images.githubusercontent.com/102292476/215440927-b9d231e7-3bba-4f78-a850-787dd20f9ded.png)
